### ISSUE TITLE
Plugin broken in Obsidian v1.2.0 insider build

### ISSUE THREAD

**Issue by henrikfalk** [ozntel/file-explorer-note-count#15]
I get these errors:

![Screenshot_20230330_011122](https://user-images.githubusercontent.com/30142914/228689100-fa5db9d3-0ce3-4f0f-a5f2-f3ce9924d0a2.png)
![Screenshot_20230330_011354](https://user-images.githubusercontent.com/30142914/228689104-f8273481-6366-456d-987b-4ba46e82d4fd.png)

**Comment by Comprehensive-Jason** [comment]
I'm also experiencing this issue.

**Comment by Wildphinn** [comment]
Have it as well. Looks like 1.2 has broken many file explorer plugins.

**Comment by ozntel** [comment]
The new release should fix the issue if you are using the insider release. Let me know if you have any issues

**Comment by henrikfalk** [comment]
The fix works :) Thank you
