### ISSUE TITLE
Does not run since last update of today

### ISSUE THREAD

**Issue by merlinuwe** [ozntel/file-explorer-note-count#16]
Let me guess: You have adapted it to the new insider release 1.2?

I cannot install it again on android

Xiaomi Poco X3 pro.

Error messages:

Failed to load plugin

Failed to unload plugin

**Comment by MrBertie** [comment]
Same problem here, Samsung A71

**Comment by follnet** [comment]
Downgrade the version from 1.2.1 to 1.2.0

**Comment by looneyapache** [comment]
Same, Not working anymore

**Comment by looneyapache** [comment]
> Downgrade the version from 1.2.1 to 1.2.0

No , That too doesn't work (at least for me)

**Comment by merlinuwe** [comment]
(At windows 10 I haven't upgraded the plugin; it works.)

**Comment by Profile8647** [comment]
Remove `data.json` from the plugin's directory if you downgraded and it should work.  Note this will remove your preferences.

**Comment by looneyapache** [comment]
> Remove `data.json` from the plugin's directory if you downgraded and it should work. Note this will reset your preferences.

I dont have data.json anywhere in given directory tree ( I am on Ubuntu 22 and use Obsidian AppImage community edition)

**Comment by willasm** [comment]
Same here. Downgrading to 1.2.0 is working.
v1.2.1 is intended for Obsidian v1.2.0 which is still in preview at this point in time.
Will wait until Obsidian update is released before trying this again.

**Comment by YousufSSyed** [comment]
How do you downgrade versions?

**Comment by ozntel** [comment]
Unfortunately, the mobile version of Obsidian doesn't validate the minimum version required for the plugin. You can see below that the minimum Obsidian version for the latest plugin update is "1.2.0":

https://github.com/ozntel/file-explorer-note-count/blob/8966745644bbcaef1fb758d8d771e3a59dd9b674/versions.json#L8

My recommendation is to use the Obsidian BRAT plugin to install the previous version of the plugin as fixed until Obsidian releases the next public version. It should only happen on mobile. The desktop should work fine since it will use the Obsidian version requirement.

**Comment by willasm** [comment]
@YousufSSyed You can download any version by clicking on releases from the code page. I just overwrote the newer version with the files from release 1.2.0. The files are in the folder `YourVaultName\.obsidian\plugins\file-explorer-note-count`

**Comment by YousufSSyed** [comment]
> Unfortunately, the mobile version of Obsidian doesn't validate the minimum version required for the plugin. You can see below that the minimum Obsidian version for the latest plugin update is "1.2.0":
> 
> https://github.com/ozntel/file-explorer-note-count/blob/8966745644bbcaef1fb758d8d771e3a59dd9b674/versions.json#L8

@ozntel What is the version.json file? Look at it, it doesn't make sense.

Also, I'm on deskop and had updated to version 1.2.1 which is broken. Can you fix it?

**Comment by looneyapache** [comment]
Finding out what went wrong in my situation took some time.

The most recent version, in my view, removed my earlier plugin folder (file-explorer-note-count), created an entirely new folder called folder-plugin-core (by aidenlx probably new requirements by latest plugin), and then put the latest plugin inside of it.

Apparently, despite deleting and re-copying version 1.2.0, this was the reason the plugin wouldn't function. 

I deleted folder-plugin-core and then restored old copy and it worked.

**Comment by ozntel** [comment]
Please delete and install the plugin again. It should work now properly. Thanks!

**Comment by merlinuwe** [comment]
You have downgraded from 1.2.1 to 1.2.0?

**Comment by ozntel** [comment]
You will get 1.2.1 update once Obsidian has its next public release

**Comment by merlinuwe** [comment]
Late, but works perfect. Tested it on Windows 10 and Android 11.

Thank you very much!

**Comment by Oneechan69** [comment]
> Unfortunately, the mobile version of Obsidian doesn't validate the minimum version required for the plugin. You can see below that the minimum Obsidian version for the latest plugin update is "1.2.0":
> 
> https://github.com/ozntel/file-explorer-note-count/blob/8966745644bbcaef1fb758d8d771e3a59dd9b674/versions.json#L8
> 
> My recommendation is to use the Obsidian BRAT plugin to install the previous version of the plugin as fixed until Obsidian releases the next public version. It should only happen on mobile. The desktop should work fine since it will use the Obsidian version requirement.

@ozntel I'm going to be blunt, I think you handled this overall situation poorly. You had released an update your plugin for a pre-release verison of Obsidian and broke for nearly everyone that was on the latest stable version, it costs $$ to get insider builds. Sure you may not have realized that, but you shouldn't have responded saying to downgrade it with BRAT. _You caused a problem with your plugin and basically told others to fix it themselves_. What about non tech-savvy users that didn't think to go to the GitHub page or see this bug? They were just left with a broken plugin that they then uninstalled and or were unhappy about being broken.

Look, I just hope you learned from this and don't do something like that again.
