### ISSUE TITLE
File count did not work since last updated

### ISSUE THREAD

**Issue by VencentYoung** [ozntel/file-explorer-note-count#17]
Obdisian Version: v1.1.16
file-explorer-note-count Version: 1.2.1

Since last updated, the plugin did not work anymore and I have tried to uninstall/reinstall the plugin and it did not help.

I checked the consol and there is some error infomation:
![image](https://user-images.githubusercontent.com/4056251/230096150-9f0dbd2c-3bc8-42d7-98d3-bdb597485dde.png)

does anyone have the same issue?

**Comment by VencentYoung** [comment]
I rolled back to V1.2.0 and it works again.
![image](https://user-images.githubusercontent.com/4056251/230103287-b6fe95a0-c654-4e04-8f6d-8ce59acfb2d3.png)

**Comment by hackerhui** [comment]
@VencentYoung you can  try novel-word-count-obsidian , also can solve the demand
https://github.com/isaaclyman/novel-word-count-obsidian
I also encountered this bug

**Comment by MSBack** [comment]
It doesn't work for me anymore either. I get several errors in the console:

```
app.js:1 Plugin failure: file-explorer-note-count TypeError: Cannot read properties of undefined (reading 'dataset')
    at removeCount (folder-count.ts:94:21)
    at eval (folder-count.ts:77:21)
    at iterateItems (misc.ts:23:9)
    at setupCount (folder-count.ts:75:5)
    at eval (fec-main.ts:79:13)
    at tryGetView (fec-main.ts:71:21)
    at doWithFileExplorer (fec-main.ts:74:13)
    at FileExplorerNoteCount.initialize (fec-main.ts:117:9)
    at FileExplorerNoteCount.onunload (fec-main.ts:129:14)
    at e.unload (app.js:1:869553)
```

and 

```
ncaught (in promise) TypeError: Cannot read properties of undefined (reading 'dataset')
    at setCount (folder-count.ts:85:17)
    at eval (folder-count.ts:78:14)
    at iterateItems (misc.ts:23:9)
    at setupCount (folder-count.ts:75:5)
    at eval (fec-main.ts:79:13)
    at tryGetView (fec-main.ts:71:21)
    at doWithFileExplorer (fec-main.ts:74:13)
    at FileExplorerNoteCount.initialize (fec-main.ts:117:9)
    at t.onLayoutReady (app.js:1:1811492)
    at FileExplorerNoteCount.eval (fec-main.ts:124:28)
```

**Comment by jerviscui** [comment]
It's not work, get the same error.

**Comment by MolaveM** [comment]
This happened to me also. To restore function, I replaced the contents of the plugin folder file-explorer-note-count with a copy from a vault backup, effectively downgrading to the previous version. Seems to have worked: the file counts have returned.

**Comment by MSBack** [comment]
@MolaveM You can also downgrade by reinstalling using the BRAT plugin: https://github.com/TfTHacker/obsidian42-brat#beta-reviewers-auto-update-tester

Using the `Install frozen version` command to install a specific version of a plugin.

**Comment by MolaveM** [comment]
@MSBack Hey thanks for the help. Now I'm starting to get what the BRAT plugin is for. Because kind of a noob.

**Comment by geekdadcodes** [comment]
> @MolaveM You can also downgrade by reinstalling using the BRAT plugin: https://github.com/TfTHacker/obsidian42-brat#beta-reviewers-auto-update-tester
> 
> Using the `Install frozen version` command to install a specific version of a plugin.

Many thanks! Had the same issue and reinstalling with BRAT solves the problem. I will stick with 1.2.0 until this bug is fixed. Thanks!

**Comment by eallion** [comment]
same

**Comment by mttransplant** [comment]
Same. Had to revert to prior version of plugin from a backup.

**Comment by ozntel** [comment]
Please delete and install the plugin again. It should work properly now. Thanks!
