### ISSUE TITLE
Failed to load plugin file-explorer-note-count

### ISSUE THREAD

**Issue by ma3252788** [ozntel/file-explorer-note-count#18]
![image](https://user-images.githubusercontent.com/22229456/235288629-9af0e477-2d67-4234-aabc-7a88b9da42be.png)

When I open Obsidian, I am prompted with this error: Failed to load plugin file-explorer-note-count

I don't know why this error occurred, even if I created a new repository and only used this plug-in, it would report an error

Obsidian：Version 1.1.16 (Installer 1.1.16)
macos：12.6.2
plugin：1.2.1

**Comment by ozntel** [comment]
Please delete and install the plugin again. It should work. Thanks!

**Comment by MSBack** [comment]
@ozntel But you didn't make a new release, how is the issue fixed?

**Comment by geekdadcodes** [comment]
@MSBack The version in the community plugins repository was revert back to 1.2.0

**Comment by Comprehensive-Jason** [comment]
@ozntel This bug is back now. I'm using Obsidian 1.6.1 and the exact same alert comes up. 
![image](https://github.com/ozntel/file-explorer-note-count/assets/68677082/29e4fd8d-a751-46b3-970b-1d9f75c2381e)
