### ISSUE TITLE
[Bug] Plugin failed to load on mobile

### ISSUE THREAD

**Issue by mathisgauthey** [ozntel/file-explorer-note-count#19]
I'm on Obsidian 1.4.3, and since this update, the plugin fails to load. I don't quite know why, it happened to icon-folder plugin too but they fixed it apparently.

Something probably changed in the way obsidian handles things.

**Comment by ozntel** [comment]
Did you try to update the plugin?

**Comment by mathisgauthey** [comment]
Yes, but it did not fix the issue. I uninstalled and reinstalled too. But the counter is not working.

I'm using a Pixel 7 android phone, android 13, on Obsidian 1.4.3(95) and using 1.2.1 version of your plugin.
