### ISSUE TITLE
总是启动时出错

### ISSUE THREAD

**Issue by liuling73** [ozntel/file-explorer-note-count#31]
近段时间，刚打开Obsidian时，该插件总是报错，需要通过设置，关闭再重启，才能正常发挥插件的功能，不知是怎么回事，是不是要升级一下，麻烦作者帮忙看看，谢谢！

**Comment by Liu8Can** [comment]
I encountered the same problem on three devices, but there is no way to troubleshoot the cause.  @ozntel 
![image](https://github.com/user-attachments/assets/41b59ad8-a855-4c09-bf77-1058ef418d92)
![image](https://github.com/user-attachments/assets/d950e6a7-a7ca-42fd-8d52-bc4133cd5999)

**Comment by Liu8Can** [comment]
> I encountered the same problem on three devices, but there is no way to troubleshoot the cause. @ozntel ![image](https://private-user-images.githubusercontent.com/102885173/383115309-41b59ad8-a855-4c09-bf77-1058ef418d92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDQyNTUsIm5iZiI6MTczMDgwMzk1NSwicGF0aCI6Ii8xMDI4ODUxNzMvMzgzMTE1MzA5LTQxYjU5YWQ4LWE4NTUtNGMwOS1iZjc3LTEwNThlZjQxOGQ5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxMDUyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjMzMGIyNWU0ZmFlOWIxMmRlOGU1ODAxOWIzYmZlZjUyODU3MjM0NTRhZmU4ODE1Mzc1YzQwNmE1OGQwYmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c8urtHIoaVNLpi6ZLipOadKPgmk-rSdXTKIZ6pxueX8) ![image](https://private-user-images.githubusercontent.com/102885173/383115320-d950e6a7-a7ca-42fd-8d52-bc4133cd5999.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDQyNTUsIm5iZiI6MTczMDgwMzk1NSwicGF0aCI6Ii8xMDI4ODUxNzMvMzgzMTE1MzIwLWQ5NTBlNmE3LWE3Y2EtNDJmZC04ZDUyLWJjNDEzM2NkNTk5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxMDUyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzQwZGY0N2EyMmZmMWIxNmE0MDJkZmY5NGJmNGQ3NTZkZDY0ODI4M2Q4NDJlZjljODZiODg3OTkzZDk4ZWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.o0NDfZZa7dQ44I2DmTcVhoaKCNEsvbRn3044hbVC7kg)

并且用同样的方式解决了这个问题，即“在设置中关闭并重新打开此插件”，但这总归不是长久之计。

**Comment by ozntel** [comment]
It should start to work after the latest release. Please check. Thanks
