### ISSUE TITLE
love this plugin! Expand to more than just markdown?

### ISSUE THREAD

**Issue by tallguyjenks** [ozntel/file-explorer-note-count#5]
turned this on and love the result! but I noticed that my media folders with `.png`'s in them are not counted, I take it the logic you have only counts markdown files? what about expanding that and adding an option to count all files, or allowing an additional option to provide file extensions in a comma separated list for what should be displayed in the counts?

**Comment by AidenLx** [comment]
You can change settings here: ![IMG_0038](https://user-images.githubusercontent.com/31102694/123534911-0e78fe80-d753-11eb-9310-7dd453406286.jpeg)
