### ISSUE TITLE
enhancement: Option to not count Folder Notes (Note has same Name as parent folder)

### ISSUE THREAD

**Issue by blaettlerio** [ozntel/file-explorer-note-count#7]
Hi,

Thank you for the nice plugin.

It would be nice if your plugin would have the option to not count folder notes (when working with one of the folder notes plugins available).

Regards,
Al

**Comment by aidenlx** [comment]
folder notes are excluded from counts by default now (make sure to install and enable [folder-note-core](https://github.com/aidenlx/folder-note-core) first)
